#spring.application.name=helpdesk

#Configuraçoes de propriedade

#habilitando o banco h2
spring.h2.console.enabled=true 

#passando o path a url que acessa o banco 
spring.h2.console.path=/h2-console

#url de config do banco
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=sa
spring.datasource.password=
#drive
spring.datasource.driver-class-name=org.h2.Driver

#mostra o sql do banco no conole
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true