#nome da aplicação
spring.application.name=helpdesk

#habilitando o console do banco H2
spring.h2.console.enabled=true

#definindo o caminho da url para acessar o console do H2
spring.h2.console.path=/h2-console


#configuração da conexão com o banco H2
#criando banco em arquivo local
spring.datasource.url=jdbc:h2:file:~/test

#usuario padrão do H2
spring.datasource.username=sa

#senha do banco (no H2 geralmente fica vazio)
spring.datasource.password=

#driver do banco H2
spring.datasource.driver-class-name=org.h2.Driver


#mostrar SQL no console do Spring
spring.jpa.show-sql=true

#formatar SQL para ficar mais legível
spring.jpa.properties.hibernate.format_sql=true